name: Build Electron App

on:
  push:
    branches: [main]

jobs:
  build-electron:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Build Electron App
        run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Electron App
          path: release/

      - name: Publish Release
        id: publish_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NAME: Huhepan
        with:
          tag_name: v${{ env.huhepan }}
          release_name: Release ${{ env.huhepan }}
          body: |
            ## Changelog
            this should be a changelog
          draft: false
          prerelease: false

      - name: Upload Assets
        id: upload-assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.publish_release.outputs.upload_url }}
          asset_path: release/*
          asset_name: Hunhepan-${{ matrix.os }}
          asset_content_type: application/octet-stream
